<Project Sdk="Microsoft.NET.Sdk">


  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\Sign.snk</AssemblyOriginatorKeyFile>
    <SGenKeyFile>..\Sign.snk</SGenKeyFile>
  </PropertyGroup>
  <ItemGroup>

    <PackageReference Include="DocsVision.Platform" Version="6.1.374" />
    <PackageReference Include="DocsVision.Platform.StorageServer.Runtime" Version="6.1.374" />
    <PackageReference Include="DocsVision.Platform.StorageServer" Version="6.1.374" />
    <PackageReference Update="DocsVision.*" ExcludeAssets="contentFiles" IncludeAssets="compile" />
  </ItemGroup>
</Project>
